version: "3"
services:
  app:
    container_name: db-media-sample-app
    build:
      context: .
      dockerfile: sample/Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./sample:/app
      - .air.toml:/app/.air.toml
    depends_on:
      - mongodb
    networks:
      - db-media-sample-network
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017

  mongodb:
    container_name: db-media-sample-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - db-media-sample-network
networks:
  db-media-sample-network:
