swagger: "2.0"
info:
  title: Sample API
  version: v1.0.0
  contact:
    email: sin392@gmail.com
  license:
    name: My License
    url: LICENSE.txt
tags:
  - name: ShopService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/shops:
    get:
      summary: |-
        ListShop
        店舗を一覧表示する
      operationId: ShopService_ListShop
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListShopResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: page
          description: ページ番号
          in: query
          required: false
          type: integer
          format: int32
        - name: perPage
          description: 1ページあたりの表示数
          in: query
          required: false
          type: integer
          format: int32
      tags:
        - ShopService
  /v1/shops/name/{name}:
    get:
      summary: |-
        FindShopByName
        店舗名で店舗を検索する
      operationId: ShopService_FindShopByName
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1FindShopByNameResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          description: 店舗名
          in: path
          required: true
          type: string
      tags:
        - ShopService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  shopv1Location:
    type: object
    properties:
      prefecture:
        type: string
        title: 県
      city:
        type: string
        title: 市
      address:
        type: string
        title: 住所
    title: Location
  v1FindShopByNameResponse:
    type: object
    properties:
      id:
        type: string
        title: 固有ID
      name:
        type: string
        title: 店舗名
      location:
        $ref: '#/definitions/shopv1Location'
        title: 住所
      tel:
        type: string
        title: 電話番号
      imageUrl:
        type: string
        title: 画像URL
      siteUrl:
        type: string
        title: サイトURL
      rating:
        type: number
        format: float
        title: 評価
      tags:
        type: array
        items:
          type: string
        title: タグのリスト
      menus:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Menu'
        title: メニューのリスト
    title: FindShopByNameResponse
  v1ListShopResponse:
    type: object
    properties:
      shops:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Shop'
        title: 店舗のリスト
    title: FindShopByNameResponse
  v1Menu:
    type: object
    properties:
      name:
        type: string
        title: 商品名
      price:
        type: integer
        format: int32
        title: 価格
      desc:
        type: string
        title: 商品説明
    title: Menu
  v1Shop:
    type: object
    properties:
      id:
        type: string
        title: 固有ID
      name:
        type: string
        title: 店舗名
      location:
        $ref: '#/definitions/shopv1Location'
        title: 住所
      tel:
        type: string
        title: 電話番号
      imageUrl:
        type: string
        title: 画像URL
      siteUrl:
        type: string
        title: サイトURL
      rating:
        type: number
        format: float
        title: 評価
      tags:
        type: array
        items:
          type: string
        title: タグのリスト
      menus:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Menu'
        title: メニューのリスト
    title: Shop
