consumes:
- application/json
definitions:
  protobufAny:
    additionalProperties: {}
    properties:
      '@type':
        type: string
    type: object
  rpcStatus:
    properties:
      code:
        format: int32
        type: integer
      details:
        items:
          $ref: '#/definitions/protobufAny'
          type: object
        type: array
      message:
        type: string
    type: object
  shopv1Location:
    properties:
      address:
        title: 住所
        type: string
      city:
        title: 市
        type: string
      prefecture:
        title: 県
        type: string
    title: Location
    type: object
  v1FindShopByNameResponse:
    properties:
      id:
        title: 固有ID
        type: string
      imageUrl:
        title: 画像URL
        type: string
      location:
        $ref: '#/definitions/shopv1Location'
        title: 住所
      menus:
        items:
          $ref: '#/definitions/v1Menu'
          type: object
        title: メニューのリスト
        type: array
      name:
        title: 店舗名
        type: string
      rating:
        format: float
        title: 評価
        type: number
      siteUrl:
        title: サイトURL
        type: string
      tags:
        items:
          type: string
        title: タグのリスト
        type: array
      tel:
        title: 電話番号
        type: string
    title: FindShopByNameResponse
    type: object
  v1Menu:
    properties:
      desc:
        title: 商品説明
        type: string
      name:
        title: 商品名
        type: string
      price:
        format: int32
        title: 価格
        type: integer
    title: Menu
    type: object
info:
  title: shop/v1/shop.proto
  version: version not set
paths:
  /v1/shops:
    get:
      operationId: ShopService_FindShopByName
      parameters:
      - description: 店舗名
        in: query
        name: name
        required: false
        type: string
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1FindShopByNameResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 店舗名で店舗を検索する
      tags:
      - ShopService
produces:
- application/json
swagger: "2.0"
tags:
- name: ShopService
