basePath: /v1
definitions:
  model.Location:
    properties:
      address:
        type: string
      city:
        type: string
      prefecture:
        description: ID         string `bson:"_id" json:"id"`
        type: string
    type: object
  model.Menu:
    properties:
      desc:
        type: string
      name:
        description: ID    string `bson:"_id" json:"id"`
        type: string
      price:
        type: integer
    type: object
  usecase.FindShopByNameOutput:
    properties:
      id:
        type: string
      image_url:
        type: string
      location:
        $ref: '#/definitions/model.Location'
      menus:
        items:
          $ref: '#/definitions/model.Menu'
        type: array
      name:
        type: string
      rating:
        type: number
      site_url:
        type: string
      tags:
        items:
          type: string
        type: array
      tel:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /shops:
    get:
      consumes:
      - application/json
      description: Retrieve a shop by name
      parameters:
      - description: 店舗の名前
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecase.FindShopByNameOutput'
      summary: 名前による店舗の一致検索（単体取得）
swagger: "2.0"
