// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type ShopTypeFindShopByNameResponse struct {
	ID       string            `json:"id"`
	ImageURL *string           `json:"image_url,omitempty"`
	Location *ShopTypeLocation `json:"location,omitempty"`
	Menus    []*ShopTypeMenu   `json:"menus,omitempty"`
	Name     string            `json:"name"`
	Rating   *float64          `json:"rating,omitempty"`
	SiteURL  *string           `json:"site_url,omitempty"`
	Tags     []*string         `json:"tags,omitempty"`
	Tel      *string           `json:"tel,omitempty"`
}

type ShopTypeListShopResponse struct {
	Shops []*ShopTypeShop `json:"shops"`
}

type ShopTypeLocation struct {
	Address    string `json:"address"`
	City       string `json:"city"`
	Prefecture string `json:"prefecture"`
}

type ShopTypeMenu struct {
	Desc  *string `json:"desc,omitempty"`
	Name  string  `json:"name"`
	Price int     `json:"price"`
}

type ShopTypeShop struct {
	ID       string            `json:"id"`
	ImageURL *string           `json:"image_url,omitempty"`
	Location *ShopTypeLocation `json:"location,omitempty"`
	Menus    []*ShopTypeMenu   `json:"menus,omitempty"`
	Name     string            `json:"name"`
	Rating   *float64          `json:"rating,omitempty"`
	SiteURL  *string           `json:"site_url,omitempty"`
	Tags     []*string         `json:"tags,omitempty"`
	Tel      *string           `json:"tel,omitempty"`
}
